workflows:
  raylib_ios_build:
    name: Raylib iOS Build Demi 💖
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Tools
        script: |
          brew install cmake ninja
      - name: Download iOS CMake Toolchain
        script: |
          mkdir -p $HOME/.cmake
          curl -L https://raw.githubusercontent.com/leetal/ios-cmake/master/ios.toolchain.cmake -o $HOME/.cmake/ios.toolchain.cmake
      - name: Clone Raylib
        script: |
          git submodule update --init --recursive
      - name: Build App
        script: |
          mkdir -p build
          cd build
          cmake .. \
            -G "Unix Makefiles" \
            -DCMAKE_TOOLCHAIN_FILE=$HOME/.cmake/ios.toolchain.cmake \
            -DPLATFORM=OS \
            -DCMAKE_BUILD_TYPE=Release
          make
      - name: Package .ipa
        script: |
          mkdir -p Payload/icon_maker.app
          cp -R build/icon_maker.app/* Payload/icon_maker.app/
          zip -r raylib_icon_maker.ipa Payload
    artifacts:
      - raylib_icon_maker.ipa
    publishing:
      app_store_connect:
      issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      private_key: $APP_STORE_CONNECT_PRIVATE_KEY
      bundle_id: $BUNDLE_ID
      app_id: $APP_STORE_APP_ID
      submit_to_testflight: true
      submit_to_app_store: true  # change to true to push live

